# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoimportsReviser < Formula
  desc "Right imports sorting & code formatting tool"
  homepage "https://github.com/incu6us/goimports-reviser"
  version "3.7.2"

  on_macos do
    on_intel do
      url "https://github.com/incu6us/goimports-reviser/releases/download/v3.7.2/goimports-reviser_3.7.2_darwin_amd64.tar.gz"
      sha256 "d5b5ddb5e8d394ffdd006ab1381f0d217f312e716c3f973ff99a5ede1c0583b3"

      def install
        bin.install "goimports-reviser"
      end
    end
    on_arm do
      url "https://github.com/incu6us/goimports-reviser/releases/download/v3.7.2/goimports-reviser_3.7.2_darwin_arm64.tar.gz"
      sha256 "291db4b7ab485ee5d9f123d72cdfa0a5d4031d4f4ca9697c78e149e47d977446"

      def install
        bin.install "goimports-reviser"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/incu6us/goimports-reviser/releases/download/v3.7.2/goimports-reviser_3.7.2_linux_amd64.tar.gz"
        sha256 "d7cfdd6f9797b3eb03c7bf1859f7c2c0c3c9d8a9244ae1e763176e7f1551ad44"

        def install
          bin.install "goimports-reviser"
        end
      end
    end
  end

  test do
    system "#{bin}/goimports-reviser -version"
  end
end
