# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoimportsReviser < Formula
  desc "Right imports sorting & code formatting tool"
  homepage "https://github.com/incu6us/goimports-reviser"
  version "3.7.3"

  on_macos do
    on_intel do
      url "https://github.com/incu6us/goimports-reviser/releases/download/v3.7.3/goimports-reviser_3.7.3_darwin_amd64.tar.gz"
      sha256 "da100e0eba738b85d05fcc7f3d630bd36b9e9afbe2512e2ba238073877f3a356"

      def install
        bin.install "goimports-reviser"
      end
    end
    on_arm do
      url "https://github.com/incu6us/goimports-reviser/releases/download/v3.7.3/goimports-reviser_3.7.3_darwin_arm64.tar.gz"
      sha256 "ddcac3f74fe75c376701d2a2be35da4d5a3ba21f031ab61ac2106008b5252c46"

      def install
        bin.install "goimports-reviser"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/incu6us/goimports-reviser/releases/download/v3.7.3/goimports-reviser_3.7.3_linux_amd64.tar.gz"
        sha256 "c8b257a77ff98a4beae25dd86f24ec81b33b63850ba746c927c1b35c81d3c0ba"

        def install
          bin.install "goimports-reviser"
        end
      end
    end
  end

  test do
    system "#{bin}/goimports-reviser -version"
  end
end
