# This file was generated by GoReleaser. DO NOT EDIT.
cask "aless" do
  version "1.0.2"

  on_macos do
    on_intel do
      url "https://github.com/incu6us/another-less/releases/download/v#{version}/aless_#{version}_darwin_amd64.tar.gz"
      sha256 "c2ea9a2a16ba4dab3fee471e0a0c0fc1ea52785999992e7b4638c1d8895de8ce"
    end
    on_arm do
      url "https://github.com/incu6us/another-less/releases/download/v#{version}/aless_#{version}_darwin_arm64.tar.gz"
      sha256 "c289634f510f7319ee1c0ffd04229987ccae74e22cc79705ca0bfc1f3411ebfe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/incu6us/another-less/releases/download/v#{version}/aless_#{version}_linux_amd64.tar.gz"
      sha256 "d7d6dc3c5af2d7985caceb9424787553458c21f69166f197fbdb58be56346081"
    end
    on_arm do
      url "https://github.com/incu6us/another-less/releases/download/v#{version}/aless_#{version}_linux_arm64.tar.gz"
      sha256 "ea8ff5a5364c2c2f0a3fb4c3b1840af1f32b3c3e60a18cbf551467101007760f"
    end
  end

  name "aless"
  desc "TUI pager for exploring and analyzing tabular data"
  homepage "https://github.com/incu6us/another-less"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aless"

  # No zap stanza required

end
