# This file was generated by GoReleaser. DO NOT EDIT.
cask "goimports-reviser" do
  version "3.13.2"

  on_macos do
    on_arm do
      sha256 "90d3f361659bdd5f8b985055f8469f88ce6e195bfa39682afaf56b52c5b67cf8"
      url "https://github.com/incu6us/goimports-reviser/releases/download/v#{version}/goimports-reviser_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2a038aa46be283c90e7447a03ce0ef7d9048d436f51dcae0b9ca5dae4c5993a4"
      url "https://github.com/incu6us/goimports-reviser/releases/download/v#{version}/goimports-reviser_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d06aabbbfc9a39f153598c1affc7fae264cddf531460961acbad9883dee78834"
      url "https://github.com/incu6us/goimports-reviser/releases/download/v#{version}/goimports-reviser_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a358c8030c55e95bb567c8d5ccc826ff88f858a16d4fb0a4a981bd772c96d469"
      url "https://github.com/incu6us/goimports-reviser/releases/download/v#{version}/goimports-reviser_#{version}_linux_amd64.tar.gz"
    end
  end

  name "goimports-reviser"
  desc "Right imports sorting & code formatting tool"
  homepage "https://github.com/incu6us/goimports-reviser"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goimports-reviser"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/goimports-reviser"]
    end
  end

  # No zap stanza required
end
