# This file was generated by GoReleaser. DO NOT EDIT.
class Ckafka < Formula
  desc "Kafka producer CLI"
  homepage "https://github.com/incu6us/ckafka"
  version "0.0.1"
  bottle :unneeded
  depends_on :linux

  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/incu6us/ckafka/releases/download/v0.0.1/ckafka_0.0.1_linux_amd64.tar.gz"
    sha256 "dbfefcec3f30c5d65895b61bcd0645aa97917794ff91b38431913b1db702d6ef"
  end

  def install
    bin.install "ckafka"
  end

  test do
    system "#{bin}/ckafka -version"
  end
end
