# This file was generated by GoReleaser. DO NOT EDIT.
class GoimportsReviser < Formula
  desc "Right imports sorting & code formatting tool"
  homepage "https://github.com/incu6us/goimports-reviser"
  version "2.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/incu6us/goimports-reviser/releases/download/v2.1.0/goimports-reviser_2.1.0_darwin_amd64.tar.gz"
    sha256 "21200ddaae5ca6e7c6142042a75d294075a3b87fb541f035001e3a6c7875824e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/incu6us/goimports-reviser/releases/download/v2.1.0/goimports-reviser_2.1.0_linux_amd64.tar.gz"
      sha256 "5b0a1106a210e5d2a77bfc90e1dfd94ba552e47512b280f7e8c8e1977ed411d2"
    end
  end

  def install
    bin.install "goimports-reviser"
  end

  test do
    system "#{bin}/goimports-reviser -version"
  end
end
