# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LokiMcpServer < Formula
  desc "MCP server exposing Grafana Loki log querying as MCP tools"
  homepage "https://github.com/incu6us/loki-mcp-server"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/incu6us/loki-mcp-server/releases/download/v0.0.3/loki-mcp-server_0.0.3_darwin_amd64.tar.gz"
      sha256 "a34bd087e07cf782329d9047faecba5989cfca5f1da8903b65819f7394f38ec9"

      define_method(:install) do
        bin.install "loki-mcp-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/incu6us/loki-mcp-server/releases/download/v0.0.3/loki-mcp-server_0.0.3_darwin_arm64.tar.gz"
      sha256 "439ff9ec7c053a2d9d2a78150d0a51349feb8b7bc9043bd97aea53de1397afec"

      define_method(:install) do
        bin.install "loki-mcp-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/incu6us/loki-mcp-server/releases/download/v0.0.3/loki-mcp-server_0.0.3_linux_amd64.tar.gz"
      sha256 "f73d1e0d8ceafd5eff209ce0863e90e9f475ea76f3f906b2e724c75484a855bb"
      define_method(:install) do
        bin.install "loki-mcp-server"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/incu6us/loki-mcp-server/releases/download/v0.0.3/loki-mcp-server_0.0.3_linux_arm64.tar.gz"
      sha256 "ff91190b1fdd3d8467bcf39558f6e6428db9d5425457fc43dbaf5055791ce9f7"
      define_method(:install) do
        bin.install "loki-mcp-server"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/loki-mcp-server --version")
  end
end
