# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenContext < Formula
  desc "MCP server providing documentation for programming languages and frameworks"
  homepage "https://github.com/incu6us/open-context"
  version "1.3.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/incu6us/open-context/releases/download/v1.3.7/open-context_1.3.7_darwin_amd64.tar.gz"
      sha256 "7779e150c971c40a5b912336afe3241e231797b2b32d1883d61885cfa842246e"

      define_method(:install) do
        bin.install "open-context"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/incu6us/open-context/releases/download/v1.3.7/open-context_1.3.7_darwin_arm64.tar.gz"
      sha256 "06002b1a4e71d9227444c10beb538098f4caf0c0d60b3b4673485f4cdb495251"

      define_method(:install) do
        bin.install "open-context"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/incu6us/open-context/releases/download/v1.3.7/open-context_1.3.7_linux_amd64.tar.gz"
      sha256 "ad0462a665fe603ac6c079fd86d2b75419c53a946280c67550d168712855b563"
      define_method(:install) do
        bin.install "open-context"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/incu6us/open-context/releases/download/v1.3.7/open-context_1.3.7_linux_arm64.tar.gz"
      sha256 "ed17acc6111c93254dae04b4debf5f277774b54ddad7d8e63c481984de4703f1"
      define_method(:install) do
        bin.install "open-context"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/open-context --version")
  end
end
